---
title: Випадкові блискітки Sense HAT
hero_image: images/banner.png
description: Нехай твій Sense HAT сяє з гордістю
original_url: https://raspberrypi.org/learning/sense-hat-random-sparkles
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: art
technologies: electronic-components, python, sense-hat
site_areas: projects
hardware: electronic-components, sense-hat
software: python
version: 4
last_tested: 2018-01-01
steps:
  - title: Вступ
  - title: Що тобі знадобиться
  - title: Підключись до свого Sense HAT
  - title: Встановлення пікселів випадковим чином
    completion:
      - engaged
  - title: Використання модуля random
  - title: Додай цикл
    completion:
      - internal
  - title: 'Завдання: кращі блискітки'
