---
title: Sense HAT random sparkles
hero_image: images/banner.png
description: Let your Sense HAT shine with pride
original_url: https://raspberrypi.org/learning/sense-hat-random-sparkles
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: art
technologies: electronic-components, python, sense-hat
site_areas: projects
hardware: electronic-components, sense-hat
software: python
version: 4
last_tested: 2018-01-01
steps:
  - 
    title: Вступ
  - 
    title: What you will need
  - 
    title: Connect to your Sense HAT
  - 
    title: Setting pixels at random
    completion:
      - engaged
  - 
    title: Using the random module
  - 
    title: Add a loop
    completion:
      - internal
  - 
    title: 'Challenge: better sparkles'
