---
title: Sense HAT lukraak knipperen
hero_image: images/banner.png
description: Laat je Sense HAT stralen
original_url: https://raspberrypi.org/learning/sense-hat-random-sparkles
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: art
technologies: electronic-components, python, sense-hat
site_areas: projects
hardware: electronic-components, sense-hat
software: python
version: 4
last_tested: 2018-01-01
steps:
  - title: Inleiding
  - title: Wat heb je nodig
  - title: Maak verbinding met je Sense HAT
  - title: Pixels willekeurig instellen
  - title: De random module gebruiken
  - title: Voeg een lus toe
  - title: "Uitdaging: betere fonkelingen"
