title: Sense HAT Random Sparkles
hero_image: images/banner.png
description: Let your Sense HAT shine with pride
original_url: https://raspberrypi.org/learning/sense-hat-random-sparkles
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Attach the Sense HAT
- title: Using set_pixel
- title: Using the random module
- title: Add a loop
- title: What next?
