---
title: Sense HAT यादृच्छिक चमक
hero_image: images/banner.png
description: अपने Sense HAT को गर्व के साथ चमकने दें
original_url: https://raspberrypi.org/learning/sense-hat-random-sparkles
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: art
technologies: electronic-components, python, sense-hat
site_areas: projects
hardware: electronic-components, sense-hat
software: python
version: 4
last_tested: 2018-01-01
steps:
- title: भूमिका
- title: आपको किन चीज़ों की आवश्यकता होगी
  completion: engaged
- title: अपने Sense HAT से कनेक्ट करें
- title: यादृच्छिक पर पिक्सेल (pixel) की स्थापना
- title: random मॉड्यूल का उपयोग करना
- title: एक लूप जोड़ें
  completion: internal
- title: 'चुनौती: बेहतर चमक'
